name: DjangoCI

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Build & Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: nicosistemas/probando-django
        tags: ${{ github.sha }}, latest
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Deploy the Docker image to the kubernetes cluster
      uses: cancue/eks-action@v0.0.2
      env:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: us-east-1
        cluster_name: stg.us-east-1.eksctl.io
      with:
        args: |
          kubectl set image deployment probando-django -n test-nico probando-django=nicosistemas/probando-django:${{ github.sha }}
          kubectl rollout status deployment/probando-django -n test-nico
